development:
  adapter: postgresql
  database: bapp_development
  username: postgres
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: bapp_test
  username: postgres
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test
